Expounding on type's table keys
MicrosoftDocs/query-docs pull request #144
Opened 2023-09-22 12:54 UTC by bgribaudo

Adding more details and examples to `Type.TableKeys`/`Type.ReplaceTableKeys`.

2023-09-26 21:01 UTC, ehrenMSFT commented on query-languages/m/type-replacetablekeys.md
> +[
This key example is kind of non-standard. What does { text } represent, for example? Not saying the way we've done it is ideal, but usually we'd describe the key format, maybe with a bulleted list of fields, and then show how it works via the examples.

2023-09-26 21:02 UTC, ehrenMSFT commented on query-languages/m/type-replacetablekeys.md
> +Replaces the key information on a table type.
```suggestion
Replace the key information on a table type.
```

2023-09-26 21:03 UTC, ehrenMSFT commented on query-languages/m/type-replacetablekeys.md
> +Clears the key information previously defined on a table type.
```suggestion
Clear the key information previously defined on a table type.
```

2023-09-26 21:05 UTC, ehrenMSFT requested changes
See my other comments.

2023-10-02 18:05 UTC, bgribaudo commented
@ehrenMSFT, thank you for the feedback and for all you do to further Power Query!

Are the revised record field descriptions more along the lines of what you are thinking?

2023-10-02 18:49 UTC, ehrenMSFT requested changes

2023-10-02 18:49 UTC, ehrenMSFT commented on query-languages/m/type-replacetablekeys.md
> +* `Columns`—a list of the column names that define the key
For lists like this, we usually use colon followed by a space.

```suggestion
* `Columns`: a list of the column names that define the key
```

The same would apply to the other bullets as well.

2023-10-03 14:15 UTC, bgribaudo commented
Thanks, @ehrenMSFT. Updated as suggested.

2023-10-03 18:03 UTC, ehrenMSFT approved these changes

2023-10-03 19:09 UTC, merged

2023-10-03 19:09 UTC, JasonWHowell commented
Thank you @bgribaudo for the extra examples!