Clarification Idea: DateTime.Date
MicrosoftDocs/query-docs pull request #168
Opened 2024-02-07 13:43 UTC by bgribaudo

2024-03-07 22:26 UTC, Jak-MS commented
@DougKlopfenstein 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-03-26 18:32 UTC, ehrenMSFT requested changes

2024-03-26 18:32 UTC, ehrenMSFT commented on query-languages/m/datetime-date.md
> +Returns the date component of value `dateTime`, if that input is a `date`, `datetime`, or `datetimezone` value. If, instead, `null` is input, `null` is returned.
```suggestion
Returns the date component of the `dateTime` parameter if the parameter is a `date`, `datetime`, or `datetimezone` value, or `null` if the parameter `null`.
```

2024-03-26 18:44 UTC, ehrenMSFT approved these changes

2024-03-27 19:30 UTC, DougKlopfenstein commented
#sign-off

2024-03-27 21:03 UTC, merged